name: RpgEssentials
main: me.duckdoom5.RpgEssentials.RpgEssentials
version: 0.1
load: startup
depend:
 - Spout

commands:
  rpg:
    description: general rpg commands
    aliases: [RPG, roleplayinggame]
    permission: rpg
    usage: |
      /rpg [command]

permissions:
  rpg.*:
    description: Gives access to all rpg commands
    default: op
    children:
      rpg.general: true